version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
    - make init
  build:
    commands:
    - make
    - make package
artifacts:
  files:
    - .aws-sam/packaged-app.yml
  discard-paths: yes
